// haut 1
plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ludexa.moteur'
    compileSdk 36

    defaultConfig {
        applicationId "com.ludexa.moteur"
        minSdk 24
        targetSdk 36
        versionCode 2
        versionName "0.1"
        // AJOUT DE SÉCURITÉ : Valeur par défaut pour calmer le compilateur
        manifestPlaceholders = [ nomApp: "Yop2D" ] 
    }

    flavorDimensions "appType"
    productFlavors {
        editeur {
            dimension "appType"
            applicationId "com.ludexa.moteur"
            manifestPlaceholders = [ nomApp: "Yop2D" ]
        }
        runner {
            dimension "appType"
            applicationId "com.yop2d.export.placeholder.xxxxxxxxxxxxxxxxxxxxx"
            manifestPlaceholders = [ nomApp: "YOP2D_GAME_NAME_PLACEHOLDER_X_X_X_X_X_X_X_X_X_X_X_" ]
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'net.lingala.zip4j:zip4j:2.11.5'
    implementation 'com.android.tools.build:apksig:8.5.0'
}
// bas 1
